services:
  - type: web
    name: trakk-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node script.js # or server.js
    branch: main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
